USE [master]
GO

/****** Object:  Database [pTable]    Script Date: 18/11/2022 20:24:44 ******/
CREATE DATABASE [pTable]

GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [pTable].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [pTable] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [pTable] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [pTable] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [pTable] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [pTable] SET ARITHABORT OFF 
GO

ALTER DATABASE [pTable] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [pTable] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [pTable] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [pTable] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [pTable] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [pTable] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [pTable] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [pTable] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [pTable] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [pTable] SET  DISABLE_BROKER 
GO

ALTER DATABASE [pTable] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [pTable] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [pTable] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [pTable] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [pTable] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [pTable] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [pTable] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [pTable] SET RECOVERY FULL 
GO

ALTER DATABASE [pTable] SET  MULTI_USER 
GO

ALTER DATABASE [pTable] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [pTable] SET DB_CHAINING OFF 
GO

ALTER DATABASE [pTable] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [pTable] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [pTable] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [pTable] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [pTable] SET QUERY_STORE = OFF
GO

ALTER DATABASE [pTable] SET  READ_WRITE 
GO

